version: 2
jobs:
  build:
    docker:
      - image: circleci/golang:1.11
    steps:
    - checkout
    - restore_cache:
        keys:
        - go_mod-{{ checksum "go.mod" }}-{{ "checksum go.sum" }}
        - go_mod-{{ checksum "go.mod" }}-
        - go_mod-
    - run: go get -v -d ./...
    - save_cache:
        key: go_mod-{{ checksum "go.mod" }}-{{ checksum "go.sum" }}
        paths:
        - /go/pkg/mod
    - run: go build -o /tmp/godplugin github.com/l2isbad/go.d.plugin/cmd/godplugin
    - run: /tmp/godplugin --help || true
    - store_artifacts:
        path: /tmp/godplugin
  vet:
    docker:
    - image: circleci/golang:1.11
    steps:
    - checkout
    - restore_cache:
        keys:
        - go.mod-{{ checksum "go.mod" }}-{{ "checksum go.sum" }}
        - go.mod-{{ checksum "go.mod" }}-
        - go.mod-
    - run: go vet ./...
  test:
    docker:
    - image: circleci/golang:1.11
    steps:
    - checkout
    - restore_cache:
        keys:
        - go.mod-{{ checksum "go.mod" }}-{{ "checksum go.sum" }}
        - go.mod-{{ checksum "go.mod" }}-
        - go.mod-
    - run: go test -v ./... -race
    - run: go test -v ./... -cover

workflows:
  version: 2
  build_and_test:
    jobs:
    - build
    - vet:
        requires:
        - build
    - test:
        requires:
        - build