version: 2
jobs:
  build:
    docker:
      - image: circleci/golang:1.11
    steps:
      - checkout
      - run: go get -v -t -d ./...
      - run: go build github.com/l2isbad/go.d.plugin/cmd/godplugin
      - run: go vet ./...
      - run: go test -v ./... -race
      - run: go test -v ./... -cover
